### ISSUE TITLE
Research MongoDB

### ISSUE THREAD

**Issue by charlesw25** [UB-CSE/course-project-a9-sleepers#10]
Research MongoDB database and setting it up for our application.

**Comment by smalbec** [comment]
- https://medium.com/javascript-in-plain-english/how-i-setup-unit-test-for-mongodb-using-jest-mongoose-103b772ee164
https://github.com/motdotla/dotenv
https://mongoosejs.com/docs/index.html

For a streamlined testing environment, MongoDB can use Jest, Mongoose and dotenv to set up a suite

**Comment by charlesw25** [comment]
[https://www.tutorialspoint.com/mongodb/index.htm](url)

- Went over database creation and deletion.
- Covered the MongoDB environment, including how to navigate the UI on Windows as well as Ubuntu.
- Discussed collections and handling records.
