### ISSUE TITLE
Research React.js

### ISSUE THREAD

**Issue by sushi-trash** [UB-CSE/course-project-a9-sleepers#11]
Research React.js library and understand the nature of components.

**Comment by smalbec** [comment]
https://www.smashingmagazine.com/2020/06/practical-guide-testing-react-applications-jest/
- React testing tool is named Jest which is used along with the popular library Enzyme, which is designed to test React components.

**Comment by sushi-trash** [comment]
https://youtu.be/mACw_G-okPE

- Javascript applications are bound to the 'root' div
- Components are the building blocks of React
- React.js utilizes JSX syntax, which is a hybrid of Javascript and HTML
- Routes are used to change the contents of a page with refreshing
