### ISSUE TITLE
Create WPM Test (Accuracy)

### ISSUE THREAD

**Issue by sushi-trash** [UB-CSE/course-project-a9-sleepers#111]
Task Tests:
-As the user types, they should be able to see how accurate they've been so far
-Hitting the wrong key will reduce the accuracy percentage
-The accuracy percentage should reset after every test

**Comment by clincl** [comment]
Current WPM checks the user input vs the actual. WPM accuracy can go down from 100% to 90% and then back to 100% if backspaced. Correct algorithm for this for more accurate percentage.
