### ISSUE TITLE
Update Calculator to Scientific (Basic Operations)

### ISSUE THREAD

**Issue by sushi-trash** [UB-CSE/course-project-a9-sleepers#96]
Task Tests:
- Current calculator is updated so that it can perform more operations
- Check that sin, cos, tan operations are functional
- Check that exponents and square roots are functional
- Make sure that the calculations performed are accurate

**Comment by clincl** [comment]
If you can, try to add as much functionality to this as possible to we don't have to go back to the calculator later for any improvements. e.g. log;ln; n!; PI input symbol. However, what you have is good enough.
